<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Array-manipulation-routines" data-toc-modified-id="Array-manipulation-routines-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Array manipulation routines</a></span></li></ul></div>

# Array manipulation routines

In [18]:
import numpy

In [19]:
import numpy as np

#### Q1. Let x be a ndarray [10, 10, 3] with all elements set to one. Reshape x so that the size of the second dimension equals 150.
#### Q1. Нехай x — масив [10, 10, 3], усі елементи якого дорівнюють одиниці. Змініть форму x так, щоб розмір другого виміру дорівнював 150.

In [174]:
x = np.ones((10, 10, 3)).reshape(1,150,2)
print(x.shape)

(1, 150, 2)


#### Q2. Let x be array [[1, 2, 3], [4, 5, 6]]. Convert it to [1 4 2 5 3 6].
#### Нехай x — це масив [[1, 2, 3], [4, 5, 6]]. Перетворіть його на [1 4 2 5 3 6].

In [181]:
x = np.array([[1, 2, 3], 
             [4, 5, 6]])
x.reshape(-1,6)
x.flatten()

array([1, 2, 3, 4, 5, 6])

#### Q3. Let x be array [[1, 2, 3], [4, 5, 6]]. Get the 5th element.
#### Нехай x — це масив [[1, 2, 3], [4, 5, 6]]. Отримайте 5-й елемент.

In [183]:
x = np.array([[1, 2, 3], [4, 5, 6]])
x.reshape(-1,6)
x = x.flatten()
x = [5]
x

[5]

#### Q4. Let x be an arbitrary 3-D array of shape (3, 4, 5). Permute the dimensions of x such that the new shape will be (4,3,5).
#### Нехай x — довільний тривимірний масив форми (3, 4, 5). Переставте розміри x так, щоб нова форма була (4,3,5).

In [54]:
x = np.array((3, 4, 5))

x[0] = 4
x[1] = 3

x

array([4, 3, 5])

#### Q5. Let x be an arbitrary 2-D array of shape (3, 4). Permute the dimensions of x such that the new shape will be (4,3).
#### Нехай x — довільний двовимірний масив форми (3, 4). Переставте розміри x так, щоб нова форма була (4,3).

In [55]:
x = np.array((3,4))
x[0] = 3
x[1] = 4
x

array([3, 4])

#### Q5. Let x be an arbitrary 2-D array of shape (3, 4). Insert a nex axis such that the new shape will be (3, 1, 4).
#### Нехай x — довільний двовимірний масив форми (3, 4). Вставте наступну вісь так, щоб нова форма була (3, 1, 4).

In [186]:
x = np.random.rand(3,4)
x.reshape(3,1,4)
x = x[:, np.newaxis, :]
x

array([[[0.54229203, 0.4436377 , 0.95704496, 0.61039815]],

       [[0.60876847, 0.1145179 , 0.83592431, 0.45874619]],

       [[0.17528661, 0.1171591 , 0.22758409, 0.94706836]]])

#### Q6. Let x be an arbitrary 3-D array of shape (3, 4, 1). Remove a single-dimensional entries such that the new shape will be (3, 4).
#### Нехай x — довільний тривимірний масив форми (3, 4, 1). Видаліть одновимірні записи так, щоб нова форма була (3, 4).

In [192]:
x = np.ones((3,4,1))
x.reshape(3,4)
np.squeeze(x)


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

#### Q7. Lex x be an array <br/>
[[ 1 2 3]<br/>
[ 4 5 6].<br/><br/>
and y be an array <br/>
[[ 7 8 9]<br/>
[10 11 12]].<br/>
Concatenate x and y so that a new array looks like <br/>[[1, 2, 3, 7, 8, 9], <br/>[4, 5, 6, 10, 11, 12]].

Lex x — масив
[[ 1 2 3]
[ 4 5 6].

і y — масив
[[ 7 8 9]

[10 11 12]].
Об’єднайте x і y, щоб новий масив виглядав так
[[1, 2, 3, 7, 8, 9],
[4, 5, 6, 10, 11, 12]].

In [104]:
x = np.array([[1, 2, 3],
              [4, 5, 6]])

y = np.array([[7, 8, 9],
              [10, 11, 12]])

x_y = np.column_stack((x, y))
print(x_y)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


#### Q8. Lex x be an array <br/>
[[ 1 2 3]<br/>
[ 4 5 6].<br/><br/>
and y be an array <br/>
[[ 7 8 9]<br/>
[10 11 12]].<br/>
Concatenate x and y so that a new array looks like <br/>[[ 1  2  3]<br/>
 [ 4  5  6]<br/>
 [ 7  8  9]<br/>
 [10 11 12]]


In [105]:
x = np.array([[1, 2, 3],
              [4, 5, 6]])

y = np.array([[7, 8, 9],
              [10, 11, 12]])

x_y = np.concatenate((x, y))
print(x_y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


#### Q8. Let x be an array [1 2 3] and y be [4 5 6]. Convert it to [[1, 4], [2, 5], [3, 6]].
#### Нехай x — масив [1 2 3], а y — [4 5 6]. Перетворіть його на [[1, 4], [2, 5], [3, 6]].

In [148]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

x_y = np.column_stack((x, y))
print(x_y)

[[1 4]
 [2 5]
 [3 6]]


#### Q9. Let x be an array [[1],[2],[3]] and y be [[4], [5], [6]]. Convert x to [[[1, 4]], [[2, 5]], [[3, 6]]].
#### Нехай x — масив [[1],[2],[3]], а y — [[4], [5], [6]]. Перетворіть x на [[[1, 4]], [[2, 5]], [[3, 6]]].

In [149]:
x = np.array([[1], [2], [3]])
y = np.array([[4], [5], [6]])

xy = np.concatenate((x, y), axis=1)[:, np.newaxis, :]
print(xy)

[[[1 4]]

 [[2 5]]

 [[3 6]]]


#### Q10. Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.
#### Нехай x — масив [1, 2, 3, ..., 9]. Розбийте x на 3 масиви, кожен з яких містить 4, 2 і 3 елементи у вихідному порядку.

In [150]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

new_x = np.split(x, [4, 6])
new_x

[array([1, 2, 3, 4]), array([5, 6]), array([7, 8, 9])]

#### Q11. Let x be an array<br/>
[[[  0.,   1.,   2.,   3.],<br/>
  [  4.,   5.,   6.,   7.]],<br/>
 
 [[  8.,   9.,  10.,  11.],<br/>
  [ 12.,  13.,  14.,  15.]]].<br/>
#### Split it into two such that the first array looks like <br/>
#### Розділіть його на два так, щоб виглядав перший масив
[[[  0.,   1.,   2.],<br/>
  [  4.,   5.,   6.]],<br/>
 
 [[  8.,   9.,  10.],<br/>
  [ 12.,  13.,  14.]]].<br/>
  
#### and the second one look like:<br/>
  
[[[  3.],<br/>
  [  7.]],<br/>
 
 [[  11.],<br/>
  [ 15.]]].<br/>  

In [151]:
x = np.array([[[0., 1., 2., 3.],
               [4., 5., 6., 7.]],
              [[8., 9., 10., 11.],
               [12., 13., 14., 15.]]])

result = np.split(x, [3, 4], axis=-1)

first_array = result[0]
second_array = result[1]

print(first_array)
print(second_array)

[[[ 0.  1.  2.]
  [ 4.  5.  6.]]

 [[ 8.  9. 10.]
  [12. 13. 14.]]]
[[[ 3.]
  [ 7.]]

 [[11.]
  [15.]]]


#### Q12. Let x be an array <br />
[[  0.,   1.,   2.,   3.],<br>
 [  4.,   5.,   6.,   7.],<br>
 [  8.,   9.,  10.,  11.],<br>
 [ 12.,  13.,  14.,  15.]].<br>
#### Split it into two arrays along the second axis.
#### Розділіть його на два масиви вздовж другої осі.

In [197]:
x = np.array([[ 0., 1., 2., 3.],
              [ 4., 5., 6., 7.],
              [ 8., 9., 10., 11.],
              [ 12., 13., 14., 15.]])

new_x = np.split(x, [2], axis=1)
x1 = new_x[0]
x2 = new_x[1]
print(x1)
print(x2)

[[ 0.  1.]
 [ 4.  5.]
 [ 8.  9.]
 [12. 13.]]
[[ 2.  3.]
 [ 6.  7.]
 [10. 11.]
 [14. 15.]]


#### Q13. Let x be an array <br />
[[  0.,   1.,   2.,   3.],<br>
 [  4.,   5.,   6.,   7.],<br>
 [  8.,   9.,  10.,  11.],<br>
 [ 12.,  13.,  14.,  15.]].<br>
#### Split it into two arrays along the first axis.
#### Розділіть його на два масиви вздовж першої осі.

In [201]:
x = np.array([[0., 1., 2., 3.],
              [4., 5., 6., 7.],
              [8., 9., 10., 11.],
              [12., 13., 14., 15.]])

new_x = np.split(x, [1], axis=0)
x1 = new_x[0]  
x2 = new_x[1] 

print(x1)
print(x2)

[[0. 1. 2. 3.]]
[[ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]


#### Q14. Let x be an array [0, 1, 2]. Convert(перетворіть) it to <br/>
[[0, 1, 2, 0, 1, 2],<br/>
 [0, 1, 2, 0, 1, 2]].

In [202]:
x = np.array([0, 1, 2])
new_x = np.tile(x, (2, 2))

print(new_x)

[[0 1 2 0 1 2]
 [0 1 2 0 1 2]]


#### Q15. Let x be an array [0, 1, 2]. Convert it to <br/>
[0, 0, 1, 1, 2, 2].

In [206]:
x = np.array([0,1,2])
result = np.repeat(x,2)
print(result)

[0 0 1 1 2 2]


#### Q16. Let x be an array [0, 0, 0, 1, 2, 3, 0, 2, 1, 0].<br/>
remove the leading the trailing zeros.

In [207]:
x = np.array([0, 0, 0, 1, 2, 3, 0, 2, 1, 0])

nonzero_indices = np.nonzero(x)
result = x[nonzero_indices[0][0]:nonzero_indices[0][-1] + 1]

print(result)

[1 2 3 0 2 1]


#### Q17. Let x be an array [2, 2, 1, 5, 4, 5, 1, 2, 3]. Get two arrays of unique elements and their counts.


In [208]:
x = np.array([2, 2, 1, 5, 4, 5, 1, 2, 3])

unique_elements, counts = np.unique(x, return_counts=True)

print(unique_elements)
print(counts)

[1 2 3 4 5]
[2 3 1 1 2]


#### Q18. Lex x be an array <br/>
[[ 1 2]<br/>
 [ 3 4].<br/>
Flip x along the second axis.

In [210]:
x = np.array([[1, 2],
              [3, 4]])

flipped_x = np.flip(x, axis=1)
print(flipped_x)

[[2 1]
 [4 3]]


#### Q19. Lex x be an array <br/>
[[ 1 2]<br/>
 [ 3 4].<br/>
Flip x along the first axis.

In [211]:
x = np.array([[1, 2],
              [3, 4]])

flipped_x = np.flip(x, axis=0)
print(flipped_x)

[[3 4]
 [1 2]]


#### Q20. Lex x be an array <br/>
[[ 1 2]<br/>
 [ 3 4].<br/>
Rotate x 90 degrees counter-clockwise.

In [212]:
x = np.array([[1, 2],
              [3, 4]])

rotated_x = np.rot90(x)
print(rotated_x)

[[2 4]
 [1 3]]


#### Q21 Lex x be an array <br/>
[[ 1 2 3 4]<br/>
 [ 5 6 7 8].<br/>
Shift elements one step to right along the second axis.

In [213]:
x = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8]])

shifted_x = np.roll(x, shift=1, axis=1)
print(shifted_x)

[[4 1 2 3]
 [8 5 6 7]]
