<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Soring,-searching,-and-counting" data-toc-modified-id="Soring,-searching,-and-counting-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Soring, searching, and counting</a></span><ul class="toc-item"><li><span><a href="#Sorting" data-toc-modified-id="Sorting-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Sorting</a></span></li><li><span><a href="#Searching" data-toc-modified-id="Searching-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Searching</a></span></li><li><span><a href="#Counting" data-toc-modified-id="Counting-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Counting</a></span></li></ul></li></ul></div>

# Soring, searching, and counting

In [3]:
import numpy as np

## Sorting

Q1. Sort x along the second axis.

In [15]:
x = np.array([[1,4],[3,1]])
y = np.sort(x, axis=1)
print(y)

[[1 4]
 [1 3]]


Q2. Sort pairs of surnames and first names and return their indices. (first by surname, then by name).

In [16]:
surnames =    ('Hertz',    'Galilei', 'Hertz')
first_names = ('Heinrich', 'Galileo', 'Gustav')
y = np.lexsort((first_names, surnames))
print(y)

[1 2 0]


Q3. Get the indices that would sort x along the second axis.

In [17]:
x = np.array([[1,4],[3,1]])
y = np.argsort(x, axis=1)
print(y)

[[0 1]
 [1 0]]


Q4. Create an array such that its fifth element would be the same as the element of sorted x, and it divide other elements by their value.

In [18]:
x = np.random.permutation(10)
sorted_value = np.sort(x)[4]
result = np.zeros_like(x)
result[4] = sorted_value
result[:4] = result[4] - 1 
result[5:] = result[4] + 1  
print("x = ", x)
print("result = ", result)


x =  [2 4 3 1 0 9 8 7 6 5]
result =  [3 3 3 3 4 5 5 5 5 5]


Q5. Create the indices of an array such that its third element would be the same as the element of sorted x, and it divide other elements by their value.

In [19]:
x = np.random.permutation(10)
sorted_value = np.sort(x)[4]
result = np.zeros_like(x)
result[4] = sorted_value
result[:4] = np.arange(4)[::-1] 
result[5:] = np.arange(1, 6)  
print("x = ", x)
print("result = ", result)

x =  [4 2 6 3 0 9 8 5 1 7]
result =  [3 2 1 0 4 1 2 3 4 5]


## Searching

Q6. Get the maximum and minimum values and their indices of x along the second axis.

In [22]:
x = np.random.permutation(10).reshape(2, 5)
max_values = np.max(x, axis=1)
max_indices = np.argmax(x, axis=1)
min_values = np.min(x, axis=1)
min_indices = np.argmin(x, axis=1)
print("x = ", x)
print("max values = ", max_values)
print("max indices:", max_indices)
print("min values = ", min_values)
print("min indices:", min_indices)


x =  [[5 0 3 8 1]
 [2 6 9 4 7]]
max values =  [8 9]
max indices: [3 2]
min values =  [0 2]
min indices: [1 0]


Q7. Get the maximum and minimum values and their indices of x along the second axis, ignoring NaNs.

In [23]:
x = np.array([[np.nan, 4], [3, 2]])
max_values = np.nanmax(x, axis=1)
max_indices = np.nanargmax(x, axis=1)
min_values = np.nanmin(x, axis=1)
min_indices = np.nanargmin(x, axis=1)
print("max values ignoring NaNs:", max_values)
print("max indices:", max_indices)
print("min values ignoring NaNs:", min_values)
print("min indices:", min_indices)

max values ignoring NaNs: [4. 3.]
max indices: [1 0]
min values ignoring NaNs: [4. 2.]
min indices: [1 1]


Q8. Get the values and indices of the elements that are bigger than 2 in x.


In [24]:
x = np.array([[1, 2, 3], [1, 3, 5]])
values = x[x > 2]
indices = np.where(x > 2)
print("values bigger than 2 =", values)
print("their indices are", indices)

values bigger than 2 = [3 3 5]
their indices are (array([0, 1, 1], dtype=int64), array([2, 1, 2], dtype=int64))


Q9. Get the indices of the elements that are bigger than 2 in the flattend x.

In [9]:
x = np.array([[1, 2, 3], [1, 3, 5]])
flattened_x = x.flatten()
all_indices = np.arange(len(flattened_x))
print(all_indices)

[0 1 2 3 4 5]


Q10. Check the elements of x and return 0 if it is less than 0, otherwise the element itself.

In [25]:
x = np.arange(-5, 4).reshape(3, 3)
result = np.where(x < 0, 0, x)
print(result)

[[0 0 0]
 [0 0 0]
 [1 2 3]]


Q11. Get the indices where elements of y should be inserted to x to maintain order.

In [26]:
x = [1, 3, 5, 7, 9]
y = [0, 4, 2, 6]
indices = np.searchsorted(x, y)
result = np.array(indices, dtype=np.int64)
print(result)

[0 2 1 3]


## Counting

Q12. Get the number of nonzero elements in x.

In [27]:
x = [[0,1,7,0,0],[3,0,0,2,19]]
y = np.count_nonzero(x)
print(y)


5
