<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Soring,-searching,-and-counting" data-toc-modified-id="Soring,-searching,-and-counting-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Soring, searching, and counting</a></span><ul class="toc-item"><li><span><a href="#Sorting" data-toc-modified-id="Sorting-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Sorting</a></span></li><li><span><a href="#Searching" data-toc-modified-id="Searching-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Searching</a></span></li><li><span><a href="#Counting" data-toc-modified-id="Counting-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Counting</a></span></li></ul></li></ul></div>

# Soring, searching, and counting

In [1]:
import numpy as np

## Sorting

Q1. Sort x along the second axis.

In [3]:
x = np.array([[1,4],[3,1]])
y = np.sort(x, axis = 1)
print(y)

[[1 4]
 [1 3]]


Q2. Sort pairs of surnames and first names and return their indices. (first by surname, then by name).

In [4]:
surnames =    ('Hertz',    'Galilei', 'Hertz')
first_names = ('Heinrich', 'Galileo', 'Gustav')
indices = np.lexsort((first_names, surnames))
print(indices)

[1 2 0]


Q3. Get the indices that would sort x along the second axis.

In [5]:
x = np.array([[1,4],[3,1]])
y = np.argsort(x, axis=1)
print(y)

[[0 1]
 [1 0]]


Q4. Create an array such that its fifth element would be the same as the element of sorted x, and it divide other elements by their value.

In [6]:
x = np.random.permutation(10)
sorted_x = np.sort(x) # sort x in ascending order
fifth = sorted_x[4] # get the fifth element of sorted x
y = np.ones(10) # create an array of ones
y[4] = fifth # set the fifth element of y to be the same as the fifth element of sorted x
y[y != fifth] = y[y != fifth] / x[y != fifth] # divide the other elements of y by their corresponding elements of x
print(y)

[0.125      0.2               inf 0.25       4.         0.14285714
 1.         0.5        0.11111111 0.16666667]


C:\Users\User\AppData\Local\Temp\ipykernel_1996\3557044158.py:6: RuntimeWarning: divide by zero encountered in divide
  y[y != fifth] = y[y != fifth] / x[y != fifth] # divide the other elements of y by their corresponding elements of x


Q5. Create the indices of an array such that its third element would be the same as the element of sorted x, and it divide other elements by their value.

In [8]:
x = np.random.permutation(10)
sorted_x = np.sort(x) # sort x in ascending order
third = sorted_x[2] # get the third element of sorted x
y = np.ones(10) # create an array of ones
y[2] = third # set the third element of y to be the same as the third element of sorted x
y[y != third] = y[y != third] / x[y != third] # divide the other elements of y by their corresponding elements of x
indices = np.argsort(y) # get the indices that would sort y in ascending order
print("indices :", indices)


indices : [9 4 5 0 8 1 6 3 2 7]


C:\Users\User\AppData\Local\Temp\ipykernel_1996\1597092197.py:6: RuntimeWarning: divide by zero encountered in divide
  y[y != third] = y[y != third] / x[y != third] # divide the other elements of y by their corresponding elements of x


## Searching

Q6. Get the maximum and minimum values and their indices of x along the second axis.

In [10]:
x = np.random.permutation(10).reshape(2, 5)
max_values = np.max(x, axis=1) 
max_indices = np.argmax(x, axis=1) 
min_values = np.min(x, axis=1)
min_indices = np.argmin(x, axis=1) 
print("x =", x)
print("maximum values =", max_values)
print("max indices =", max_indices)
print("minimum values =", min_values)
print("min indices =", min_indices)

x = [[4 7 8 2 3]
 [5 6 0 9 1]]
maximum values = [8 9]
max indices = [2 3]
minimum values = [2 0]
min indices = [3 2]


Q7. Get the maximum and minimum values and their indices of x along the second axis, ignoring NaNs.

In [12]:
x = np.array([[np.nan, 4], [3, 2]])
max_values = np.nanmax(x, axis=1) 
max_indices = np.nanargmax(x, axis=1) 
min_values = np.nanmin(x, axis=1) 
min_indices = np.nanargmin(x, axis=1) 
print("maximum values ignoring NaNs =", max_values)
print("max indices =", max_indices)
print("minimum values ignoring NaNs =", min_values)
print("min indices =", min_indices)

maximum values ignoring NaNs = [4. 3.]
max indices = [1 0]
minimum values ignoring NaNs = [4. 2.]
min indices = [1 1]


Q8. Get the values and indices of the elements that are bigger than 2 in x.


In [13]:
x = np.array([[1, 2, 3], [1, 3, 5]])
condition = x > 2
indices = np.where(condition) 
values = x[indices] 
print("Values bigger than 2 =", values)
print("Their indices are ", indices)

Values bigger than 2 = [3 3 5]
Their indices are  (array([0, 1, 1], dtype=int64), array([2, 1, 2], dtype=int64))


Q9. Get the indices of the elements that are bigger than 2 in the flattend x.

In [14]:
x = np.array([[1, 2, 3], [1, 3, 5]])
flat_x = np.ravel(x) 
print(flat_x)

[1 2 3 1 3 5]


Q10. Check the elements of x and return 0 if it is less than 0, otherwise the element itself.

In [15]:
x = np.arange(-5, 4).reshape(3, 3)
y = np.where(x < 0, 0, x)
print(y)

[[0 0 0]
 [0 0 0]
 [1 2 3]]


Q11. Get the indices where elements of y should be inserted to x to maintain order.

In [21]:
x = [1, 3, 5, 7, 9]
y = [0, 4, 2, 6]
indices = np.searchsorted(x, y, ) 
print(indices )

[0 2 1 3]


## Counting

Q12. Get the number of nonzero elements in x.

In [22]:
x = [[0,1,7,0,0],[3,0,0,2,19]]
y = np.count_nonzero(x) 
print(y)

5
