<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Soring,-searching,-and-counting" data-toc-modified-id="Soring,-searching,-and-counting-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Soring, searching, and counting</a></span><ul class="toc-item"><li><span><a href="#Sorting" data-toc-modified-id="Sorting-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Sorting</a></span></li><li><span><a href="#Searching" data-toc-modified-id="Searching-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Searching</a></span></li><li><span><a href="#Counting" data-toc-modified-id="Counting-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Counting</a></span></li></ul></li></ul></div>

# Soring, searching, and counting

In [3]:
import numpy

In [4]:
import numpy as np

## Sorting

Q1. Sort x along the second axis.
(Відсортуйте x уздовж другої осі.)

In [5]:
x = np.array([[1,4],[3,1]])
sort_x = np.sort(x, axis=1)
print(sort_x)

[[1 4]
 [1 3]]


Q2. Sort pairs of surnames and first names and return their indices. (first by surname, then by name).
(Відсортуйте пари прізвищ та імен і поверніть їхні індекси. (спочатку по прізвищу, потім по імені).)

In [6]:
surnames =    ('Hertz',    'Galilei', 'Hertz')
first_names = ('Heinrich', 'Galileo', 'Gustav')
result = np.lexsort((first_names, surnames))
print(result)

[1 2 0]


Q3. Get the indices that would sort x along the second axis. (Отримайте індекси, які б сортували x уздовж другої осі.)

In [64]:
x = np.array([[1,4],[3,1]])
result = np.argsort(x, axis=1)
print(result)

[[0 1]
 [1 0]]


Q4. Create an array such that its fifth element would be the same as the element of sorted x, and it divide other elements by their value. (Створіть такий масив, щоб його п’ятий елемент був таким самим, як і елемент відсортованого x, а інші елементи розділив на їх значення.)

In [77]:
x = np.random.permutation(10)

sorted_value = np.sort(x)[4]

result = np.zeros_like(x)
result[4] = sorted_value

result[:4] = result[4] - 1 
result[5:] = result[4] + 1  

print("x = ", x)
print("result = ", result)



x =  [0 5 6 2 4 7 1 9 8 3]
result =  [3 3 3 3 4 5 5 5 5 5]


Q5. Create the indices of an array such that its third element would be the same as the element of sorted x, and it divide other elements by their value.(Створіть індекси масиву так, щоб його третій елемент збігався з елементом відсортованого x, а інші елементи розділив на їх значення.)

In [78]:
x = np.random.permutation(10)

sorted_value = np.sort(x)[4]

result = np.zeros_like(x)
result[4] = sorted_value
result[:4] = np.arange(4)[::-1] 
result[5:] = np.arange(1, 6)  

print("x = ", x)
print("result = ", result)

x =  [6 2 9 8 4 0 5 1 3 7]
result =  [3 2 1 0 4 1 2 3 4 5]


## Searching

Q6. Get the maximum and minimum values and their indices of x along the second axis. (Отримайте максимальне та мінімальне значення та їхні індекси x уздовж другої осі.)

In [79]:
x = np.random.permutation(10).reshape(2, 5)

max_values = np.max(x, axis=1)
max_indices = np.argmax(x, axis=1)


min_values = np.min(x, axis=1)
min_indices = np.argmin(x, axis=1)

print("x = ", x)
print("maximum values = ", max_values)
print("max indices:", max_indices)
print("minimum values = ", min_values)
print("min indices:", min_indices)



x =  [[9 4 2 3 8]
 [7 5 6 1 0]]
maximum values =  [9 7]
max indices: [0 0]
minimum values =  [2 0]
min indices: [2 4]


Q7. Get the maximum and minimum values and their indices of x along the second axis, ignoring NaNs.
(Отримайте максимальне та мінімальне значення та їхні індекси x уздовж другої осі, ігноруючи NaN.)

In [80]:
x = np.array([[np.nan, 4], [3, 2]])

max_values = np.nanmax(x, axis=1)
max_indices = np.nanargmax(x, axis=1)

min_values = np.nanmin(x, axis=1)
min_indices = np.nanargmin(x, axis=1)

print("maximum values ignoring NaNs:", max_values)
print("max indices:", max_indices)
print("minimum values ignoring NaNs:", min_values)
print("min indices:", min_indices)


maximum values ignoring NaNs: [4. 3.]
max indices: [1 0]
minimum values ignoring NaNs: [4. 2.]
min indices: [1 1]


Q8. Get the values and indices of the elements that are bigger than 2 in x.
(Отримайте значення та індекси елементів, які більші за 2 у x.)

In [81]:
x = np.array([[1, 2, 3], [1, 3, 5]])
values = x[x > 2]
indices = np.where(x > 2)

print("values bigger than 2 =", values)
print("their indices are", indices)

values bigger than 2 = [3 3 5]
their indices are (array([0, 1, 1]), array([2, 1, 2]))


 Q9. Get the indices of the elements that are bigger than 2 in the flattend x.
 (Отримайте індекси елементів, які більші за 2 у flattend x.)

In [93]:
x = np.array([[1, 2, 3], [1, 3, 5]])

flattened_x = x.flatten()

all_indices = np.arange(len(flattened_x))

print(all_indices)


[0 1 2 3 4 5]


Q10. Check the elements of x and return 0 if it is less than 0, otherwise the element itself.
(Перевірте елементи x і поверніть 0, якщо він менший за 0, інакше сам елемент.)

In [39]:
x = np.arange(-5, 4).reshape(3, 3)

result = np.where(x < 0, 0, x)
print(result)

[[0 0 0]
 [0 0 0]
 [1 2 3]]


Q11. Get the indices where elements of y should be inserted to x to maintain order.
(Отримайте індекси, де елементи y повинні бути вставлені в x для підтримки порядку.)

In [40]:
x = [1, 3, 5, 7, 9]
y = [0, 4, 2, 6]

result = np.searchsorted(x, y)
result

array([0, 2, 1, 3])

## Counting

Q12. Get the number of nonzero elements in x. 
( Отримайте кількість ненульових елементів у x. )

In [41]:
x = [[0,1,7,0,0],[3,0,0,2,19]]

count = np.count_nonzero(x)
print(count)

5
